name: CI

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Run ruff via nox"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9"
          python-version: "3.14"

      - name: Run ruff via nox
        run: |
          uv run nox -s format

  pyright:
    runs-on: ubuntu-latest
    name: "Run pyright via nox"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9"
          python-version: "3.14"

      - name: Run pyright via nox
        run: |
          uv run nox -s pyright

  slotscheck:
    runs-on: ubuntu-latest
    name: "Run slotscheck via nox"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9"
          python-version: "3.14"

      - name: Run slotscheck via nox
        run: |
          uv run nox -s slotscheck

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    name: Run pytest via nox on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9"
          python-version: ${{ matrix.python-version }}
      - run: |
          uv run nox -s pytest
